export const dummyCourses = [
    {
        id: 1729283473238,
        title: 'Frontend Developers',
        description: 'Learn the fundamentals of frontend development.',
        instructor: 'PRATIK',
        category: 'Frontend Developer',
        fees: '200',
        enrolled: false,
        progress: 0,
        videoLink: 'https://www.youtube.com/watch?v=83_7HQuIQfU',
    },
    {
        id: 1729283473239,
        title: 'Advanced CSS Techniques',
        description: 'Master advanced techniques in CSS for responsive designs.',
        instructor: 'PRATIK',
        category: 'Frontend Developer',
        fees: '250',
        enrolled: false,
        progress: 0,
        videoLink: 'https://www.youtube.com/watch?v=Qhaz36TZG5Y',
    },
    {
        id: 1729283473240,
        title: 'JavaScript Essentials',
        description: 'Understand the core concepts of JavaScript.',
        instructor: 'PRATIK',
        category: 'Frontend Developer',
        fees: '300',
        enrolled: false,
        progress: 0,
        videoLink: 'https://www.youtube.com/watch?v=lkIFF4maKMU',
    },
    {
        id: 1729283473241,
        title: 'React for Beginners',
        description: 'Get started with React and build your first app.',
        instructor: 'PRATIK',
        category: 'Frontend Developer',
        fees: '400',
        enrolled: false,
        progress: 0,
        videoLink: 'https://www.youtube.com/watch?v=2OTq15A5s0Y',
    },
    {
        id: 1729283473242,
        title: 'Understanding APIs',
        description: 'Learn how to work with APIs in JavaScript.',
        instructor: 'PRATIK',
        category: 'Frontend Developer',
        fees: '350',
        enrolled: false,
        progress: 0,
        videoLink: 'https://www.youtube.com/watch?v=ByGJQzlzxQg',
    },
];
